---
- name: Install and Start Nginx
  hosts: webservers
  become: yes

  tasks:
    - name: Update apt package cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Ensure Nginx is started and enabled
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Print a success message
      ansible.builtin.debug:
        msg: "Nginx has been installed and is running."